import type { Locale } from '@/lib/types'

/**
 * Public, unauthenticated link to a single fact — see
 * src/features/share/SharedFactPage.tsx and the `to anon` read policy on
 * the `facts` table in supabase/schema.sql.
 *
 * The sharer's locale rides along as `?lang=` so the link preview
 * (generated by middleware.ts / api/og.tsx, which can't know the
 * recipient) shows the fact in the language the sharer actually read it
 * in. Omitted for English, which is the default anyway, to keep the
 * common link clean.
 */
export function factShareUrl(factId: string, locale: Locale = 'en'): string {
  const base = `${window.location.origin}/f/${factId}`
  return locale === 'en' ? base : `${base}?lang=${locale}`
}
